language: generic

notifications:
  email:
    - maxim@synrc.com
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: change  # options: [always|never|change] default: always
    on_start:   always  # options: [always|never|change] default: always

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - git clone git://github.com/mortberg/cubicaltt && cd cubicaltt
  - stack build
  - CUBICAL=$(stack path --local-install-root)/bin/cubical
  - cd ..
  - $CUBICAL -b src/k_thery.ctt
  - $CUBICAL -b src/nat_theory.ctt
  - $CUBICAL -b src/category.ctt
  - $CUBICAL -b src/homotopy.ctt
