language: generic

notifications:
  email:
    - maxim@synrc.com
  webhooks:
    on_success: change
    on_failure: change
    on_start:   always

cache:
  directories:
  - $HOME/.stack

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - ARCH=https://www.stackage.org/stack/linux-x86_64
  - travis_retry curl -L $ARCH | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - git clone git://github.com/mortberg/cubicaltt && cd cubicaltt
  - stack build
  - CUBICAL=$(stack path --local-install-root)/bin/cubical
  - cd ..
  - for i in src/*; do $CUBICAL -b $i; done
